/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as NasilCalisiyoruzRouteImport } from './routes/nasil-calisiyoruz'
import { Route as SssRouteImport } from './routes/sss'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisiyoruzRoute = NasilCalisiyoruzRouteImport.update({
  id: '/nasil-calisiyoruz',
  path: '/nasil-calisiyoruz',
  getParentRoute: () => rootRouteImport,
} as any)
const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-calisiyoruz': typeof NasilCalisiyoruzRoute
  '/sss': typeof SssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-calisiyoruz': typeof NasilCalisiyoruzRoute
  '/sss': typeof SssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-calisiyoruz': typeof NasilCalisiyoruzRoute
  '/sss': typeof SssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/nasil-calisiyoruz'
    | '/sss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/nasil-calisiyoruz'
    | '/sss'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/nasil-calisiyoruz'
    | '/sss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  NasilCalisiyoruzRoute: typeof NasilCalisiyoruzRoute
  SssRoute: typeof SssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisiyoruz': {
      id: '/nasil-calisiyoruz'
      path: '/nasil-calisiyoruz'
      fullPath: '/nasil-calisiyoruz'
      preLoaderRoute: typeof NasilCalisiyoruzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  NasilCalisiyoruzRoute: NasilCalisiyoruzRoute,
  SssRoute: SssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
